output "blog_url" {
  description = "Public URL for the blog."
  value       = "https://${var.domain_name}"
}

output "alb_dns_name" {
  description = "ALB DNS name."
  value       = aws_lb.main.dns_name
}

output "app_instance_id" {
  description = "EC2 instance ID for SSM deployment."
  value       = aws_instance.app.id
}

output "rds_endpoint" {
  description = "Private RDS endpoint."
  value       = aws_db_instance.main.address
}

output "rds_master_secret_arn" {
  description = "Secrets Manager ARN generated by RDS for the master credentials."
  value       = aws_db_instance.main.master_user_secret[0].secret_arn
}

output "app_secret_arn" {
  description = "Secrets Manager ARN for application runtime configuration."
  value       = aws_secretsmanager_secret.app.arn
}

output "route53_zone_id" {
  description = "Existing Route 53 hosted zone used by this stack."
  value       = data.aws_route53_zone.main.zone_id
}
